// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGMdFtIYY7Q1yCONlnyO6tWWdm2WdJ8S0',
    appId: '1:455818284149:web:14fd81dfa4041af141fc3c',
    messagingSenderId: '455818284149',
    projectId: 'prueba-ancient',
    authDomain: 'prueba-ancient.firebaseapp.com',
    storageBucket: 'prueba-ancient.appspot.com',
    measurementId: 'G-F48VH0H2XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4VWC_9on5RXFmbfB9YhCT6lhxa4fEWBQ',
    appId: '1:455818284149:android:be8c66be7f0a693441fc3c',
    messagingSenderId: '455818284149',
    projectId: 'prueba-ancient',
    storageBucket: 'prueba-ancient.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm9Oo7cN5YJ0VNNCKK_cENQE-hAuXN6nk',
    appId: '1:455818284149:ios:e86531d907556dea41fc3c',
    messagingSenderId: '455818284149',
    projectId: 'prueba-ancient',
    storageBucket: 'prueba-ancient.appspot.com',
    iosBundleId: 'com.example.pruebaAncient',
  );
}
